[package]
name = "scanner"
version = "0.1.0"
edition = "2021"
authors = ["Luís Góis <ShellTux@Github"]
description = "Scanner is a simple utility to parse strings, numbers, ..."
license = "MIT"
readme = "./README.md"
keywords = ["scanner"]

[dependencies]
